server:
    port: 8181

google:
    client:
      clientId: {{CLIENT_ID_GOOGLE_APP}}
      clientSecret: {{CLIENT_SECRET_GOOGLE_APP}}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
